name: Unzip File

on:
  push:
    paths:
      - '**.zip'  # Runs only when a ZIP file is pushed
  workflow_dispatch:  # Allows manual triggering

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Find and Unzip ZIP Files
        run: |
          for file in $(find . -name "*.zip"); do
            unzip "$file" -d "$(dirname "$file")"
            rm "$file"  # Optional: Remove the ZIP after extraction
          done

      - name: Commit and Push Extracted Files
        run: |
          git config --global user.name "Addiction35"
          git config --global user.email "brianmanotmgk@gmail.com.com"
          git add .
          git commit -m "Extracted ZIP files"
          git push
